version: '3.8'
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=Kd??60521MyBeast
      - N8N_HOST=0.0.0.0
      - WEBHOOK_URL=https://YOUR_DOMAIN
      - GENERIC_TIMEZONE=Asia/Jerusalem
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  n8n_data:
