FROM node:20-alpine

RUN npm install -g n8n

ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=10000
ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=Memadims2025!
ENV GENERIC_TIMEZONE=Asia/Jerusalem

WORKDIR /data

EXPOSE 10000

CMD ["n8n", "start"]
